package com.cna.facturita.core.loader.tenant;

import com.cna.facturita.core.model.tenant.Pais;
import com.cna.facturita.core.repository.tenant.PaisRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.util.Arrays;
import java.util.List;

@Component
public class PaisDataLoader {

    private static final Logger log = LoggerFactory.getLogger(PaisDataLoader.class);

    private final PaisRepository paisRepository;

    public PaisDataLoader(PaisRepository paisRepository) {
        this.paisRepository = paisRepository;
    }

    public void cargaInicial() {
        log.info("=== Iniciando carga de datos demo para Países ===");

        if (paisRepository.count() > 0) {
            log.info("Ya existen países en la base de datos. Saltando creación de datos demo.");
            return;
        }

        List<Pais> paises = Arrays.asList(
            new Pais("AX", "AALAND ISLANDS", true),
            new Pais("AF", "AFGHANISTAN", true),
            new Pais("AL", "ALBANIA", true),
            new Pais("DZ", "ALGERIA", true),
            new Pais("AS", "AMERICAN SAMOA", true),
            new Pais("AD", "ANDORRA", true),
            new Pais("AO", "ANGOLA", true),
            new Pais("AI", "ANGUILLA", true),
            new Pais("AQ", "ANTARCTICA", true),
            new Pais("AG", "ANTIGUA AND BARBUDA", true),
            new Pais("AR", "ARGENTINA", true),
            new Pais("AM", "ARMENIA", true),
            new Pais("AW", "ARUBA", true),
            new Pais("AU", "AUSTRALIA", true),
            new Pais("AT", "AUSTRIA", true),
            new Pais("AZ", "AZERBAIJAN", true),
            new Pais("BS", "BAHAMAS", true),
            new Pais("BH", "BAHRAIN", true),
            new Pais("BD", "BANGLADESH", true),
            new Pais("BB", "BARBADOS", true),
            new Pais("BY", "BELARUS", true),
            new Pais("BE", "BELGIUM", true),
            new Pais("BZ", "BELIZE", true),
            new Pais("BJ", "BENIN", true),
            new Pais("BM", "BERMUDA", true),
            new Pais("BT", "BHUTAN", true),
            new Pais("BO", "BOLIVIA", true),
            new Pais("BA", "BOSNIA AND HERZEGOWINA", true),
            new Pais("BW", "BOTSWANA", true),
            new Pais("BV", "BOUVET ISLAND", true),
            new Pais("BR", "BRAZIL", true),
            new Pais("IO", "BRITISH INDIAN OCEAN TERRITORY", true),
            new Pais("BN", "BRUNEI DARUSSALAM", true),
            new Pais("BG", "BULGARIA", true),
            new Pais("BF", "BURKINA FASO", true),
            new Pais("BI", "BURUNDI", true),
            new Pais("KH", "CAMBODIA", true),
            new Pais("CM", "CAMEROON", true),
            new Pais("CA", "CANADA", true),
            new Pais("CV", "CAPE VERDE", true),
            new Pais("KY", "CAYMAN ISLANDS", true),
            new Pais("CF", "CENTRAL AFRICAN REPUBLIC", true),
            new Pais("TD", "CHAD", true),
            new Pais("CL", "CHILE", true),
            new Pais("CN", "CHINA", true),
            new Pais("CX", "CHRISTMAS ISLAND", true),
            new Pais("CC", "COCOS (KEELING) ISLANDS", true),
            new Pais("CO", "COLOMBIA", true),
            new Pais("KM", "COMOROS", true),
            new Pais("CD", "CONGO, Democratic Republic of (was Zaire)", true),
            new Pais("CG", "CONGO, Republic of", true),
            new Pais("CK", "COOK ISLANDS", true),
            new Pais("CR", "COSTA RICA", true),
            new Pais("CI", "COTE D`IVOIRE", true),
            new Pais("HR", "CROATIA (local name: Hrvatska)", true),
            new Pais("CU", "CUBA", true),
            new Pais("CY", "CYPRUS", true),
            new Pais("CZ", "CZECH REPUBLIC", true),
            new Pais("DK", "DENMARK", true),
            new Pais("DJ", "DJIBOUTI", true),
            new Pais("DM", "DOMINICA", true),
            new Pais("DO", "DOMINICAN REPUBLIC", true),
            new Pais("EC", "ECUADOR", true),
            new Pais("EG", "EGYPT", true),
            new Pais("SV", "EL SALVADOR", true),
            new Pais("GQ", "EQUATORIAL GUINEA", true),
            new Pais("ER", "ERITREA", true),
            new Pais("EE", "ESTONIA", true),
            new Pais("ET", "ETHIOPIA", true),
            new Pais("FK", "FALKLAND ISLANDS (MALVINAS)", true),
            new Pais("FO", "FAROE ISLANDS", true),
            new Pais("FJ", "FIJI", true),
            new Pais("FI", "FINLAND", true),
            new Pais("FR", "FRANCE", true),
            new Pais("GF", "FRENCH GUIANA", true),
            new Pais("PF", "FRENCH POLYNESIA", true),
            new Pais("TF", "FRENCH SOUTHERN TERRITORIES", true),
            new Pais("GA", "GABON", true),
            new Pais("GM", "GAMBIA", true),
            new Pais("GE", "GEORGIA", true),
            new Pais("DE", "GERMANY", true),
            new Pais("GH", "GHANA", true),
            new Pais("GI", "GIBRALTAR", true),
            new Pais("GR", "GREECE", true),
            new Pais("GL", "GREENLAND", true),
            new Pais("GD", "GRENADA", true),
            new Pais("GP", "GUADELOUPE", true),
            new Pais("GU", "GUAM", true),
            new Pais("GT", "GUATEMALA", true),
            new Pais("GN", "GUINEA", true),
            new Pais("GW", "GUINEA-BISSAU", true),
            new Pais("GY", "GUYANA", true),
            new Pais("HT", "HAITI", true),
            new Pais("HM", "HEARD AND MC DONALD ISLANDS", true),
            new Pais("HN", "HONDURAS", true),
            new Pais("HK", "HONG KONG", true),
            new Pais("HU", "HUNGARY", true),
            new Pais("IS", "ICELAND", true),
            new Pais("IN", "INDIA", true),
            new Pais("ID", "INDONESIA", true),
            new Pais("IR", "IRAN (ISLAMIC REPUBLIC OF)", true),
            new Pais("IQ", "IRAQ", true),
            new Pais("IE", "IRELAND", true),
            new Pais("IL", "ISRAEL", true),
            new Pais("IT", "ITALY", true),
            new Pais("JM", "JAMAICA", true),
            new Pais("JP", "JAPAN", true),
            new Pais("JO", "JORDAN", true),
            new Pais("KZ", "KAZAKHSTAN", true),
            new Pais("KE", "KENYA", true),
            new Pais("KI", "KIRIBATI", true),
            new Pais("KP", "KOREA, DEMOCRATIC PEOPLE`S REPUBLIC OF", true),
            new Pais("KR", "KOREA, REPUBLIC OF", true),
            new Pais("KW", "KUWAIT", true),
            new Pais("KG", "KYRGYZSTAN", true),
            new Pais("LA", "LAO PEOPLE`S DEMOCRATIC REPUBLIC", true),
            new Pais("LV", "LATVIA", true),
            new Pais("LB", "LEBANON", true),
            new Pais("LS", "LESOTHO", true),
            new Pais("LR", "LIBERIA", true),
            new Pais("LY", "LIBYAN ARAB JAMAHIRIYA", true),
            new Pais("LI", "LIECHTENSTEIN", true),
            new Pais("LT", "LITHUANIA", true),
            new Pais("LU", "LUXEMBOURG", true),
            new Pais("MO", "MACAU", true),
            new Pais("MK", "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF", true),
            new Pais("MG", "MADAGASCAR", true),
            new Pais("MW", "MALAWI", true),
            new Pais("MY", "MALAYSIA", true),
            new Pais("MV", "MALDIVES", true),
            new Pais("ML", "MALI", true),
            new Pais("MT", "MALTA", true),
            new Pais("MH", "MARSHALL ISLANDS", true),
            new Pais("MQ", "MARTINIQUE", true),
            new Pais("MR", "MAURITANIA", true),
            new Pais("MU", "MAURITIUS", true),
            new Pais("YT", "MAYOTTE", true),
            new Pais("MX", "MEXICO", true),
            new Pais("FM", "MICRONESIA, FEDERATED STATES OF", true),
            new Pais("MD", "MOLDOVA, REPUBLIC OF", true),
            new Pais("MC", "MONACO", true),
            new Pais("MN", "MONGOLIA", true),
            new Pais("MS", "MONTSERRAT", true),
            new Pais("MA", "MOROCCO", true),
            new Pais("MZ", "MOZAMBIQUE", true),
            new Pais("MM", "MYANMAR", true),
            new Pais("NA", "NAMIBIA", true),
            new Pais("NR", "NAURU", true),
            new Pais("NP", "NEPAL", true),
            new Pais("NL", "NETHERLANDS", true),
            new Pais("AN", "NETHERLANDS ANTILLES", true),
            new Pais("NC", "NEW CALEDONIA", true),
            new Pais("NZ", "NEW ZEALAND", true),
            new Pais("NI", "NICARAGUA", true),
            new Pais("NE", "NIGER", true),
            new Pais("NG", "NIGERIA", true),
            new Pais("NU", "NIUE", true),
            new Pais("NF", "NORFOLK ISLAND", true),
            new Pais("MP", "NORTHERN MARIANA ISLANDS", true),
            new Pais("NO", "NORWAY", true),
            new Pais("OM", "OMAN", true),
            new Pais("PK", "PAKISTAN", true),
            new Pais("PW", "PALAU", true),
            new Pais("PS", "PALESTINIAN TERRITORY, Occupied", true),
            new Pais("PA", "PANAMA", true),
            new Pais("PG", "PAPUA NEW GUINEA", true),
            new Pais("PY", "PARAGUAY", true),
            new Pais("PE", "PERU", true),
            new Pais("PH", "PHILIPPINES", true),
            new Pais("PN", "PITCAIRN", true),
            new Pais("PL", "POLAND", true),
            new Pais("PT", "PORTUGAL", true),
            new Pais("PR", "PUERTO RICO", true),
            new Pais("QA", "QATAR", true),
            new Pais("RE", "REUNION", true),
            new Pais("RO", "ROMANIA", true),
            new Pais("RU", "RUSSIAN FEDERATION", true),
            new Pais("RW", "RWANDA", true),
            new Pais("SH", "SAINT HELENA", true),
            new Pais("KN", "SAINT KITTS AND NEVIS", true),
            new Pais("LC", "SAINT LUCIA", true),
            new Pais("PM", "SAINT PIERRE AND MIQUELON", true),
            new Pais("VC", "SAINT VINCENT AND THE GRENADINES", true),
            new Pais("WS", "SAMOA", true),
            new Pais("SM", "SAN MARINO", true),
            new Pais("ST", "SAO TOME AND PRINCIPE", true),
            new Pais("SA", "SAUDI ARABIA", true),
            new Pais("SN", "SENEGAL", true),
            new Pais("CS", "SERBIA AND MONTENEGRO", true),
            new Pais("SC", "SEYCHELLES", true),
            new Pais("SL", "SIERRA LEONE", true),
            new Pais("SG", "SINGAPORE", true),
            new Pais("SK", "SLOVAKIA", true),
            new Pais("SI", "SLOVENIA", true),
            new Pais("SB", "SOLOMON ISLANDS", true),
            new Pais("SO", "SOMALIA", true),
            new Pais("ZA", "SOUTH AFRICA", true),
            new Pais("GS", "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS", true),
            new Pais("ES", "SPAIN", true),
            new Pais("LK", "SRI LANKA", true),
            new Pais("SD", "SUDAN", true),
            new Pais("SR", "SURINAME", true),
            new Pais("SJ", "SVALBARD AND JAN MAYEN ISLANDS", true),
            new Pais("SZ", "SWAZILAND", true),
            new Pais("SE", "SWEDEN", true),
            new Pais("CH", "SWITZERLAND", true),
            new Pais("SY", "SYRIAN ARAB REPUBLIC", true),
            new Pais("TW", "TAIWAN", true),
            new Pais("TJ", "TAJIKISTAN", true),
            new Pais("TZ", "TANZANIA, UNITED REPUBLIC OF", true),
            new Pais("TH", "THAILAND", true),
            new Pais("TL", "TIMOR-LESTE", true),
            new Pais("TG", "TOGO", true),
            new Pais("TK", "TOKELAU", true),
            new Pais("TO", "TONGA", true),
            new Pais("TT", "TRINIDAD AND TOBAGO", true),
            new Pais("TN", "TUNISIA", true),
            new Pais("TR", "TURKEY", true),
            new Pais("TM", "TURKMENISTAN", true),
            new Pais("TC", "TURKS AND CAICOS ISLANDS", true),
            new Pais("TV", "TUVALU", true),
            new Pais("UG", "UGANDA", true),
            new Pais("UA", "UKRAINE", true),
            new Pais("AE", "UNITED ARAB EMIRATES", true),
            new Pais("GB", "UNITED KINGDOM", true),
            new Pais("US", "UNITED STATES", true),
            new Pais("UM", "UNITED STATES MINOR OUTLYING ISLANDS", true),
            new Pais("UY", "URUGUAY", true),
            new Pais("UZ", "UZBEKISTAN", true),
            new Pais("VU", "VANUATU", true),
            new Pais("VA", "VATICAN CITY STATE (HOLY SEE)", true),
            new Pais("VE", "VENEZUELA", true),
            new Pais("VN", "VIET NAM", true),
            new Pais("VG", "VIRGIN ISLANDS (BRITISH)", true),
            new Pais("VI", "VIRGIN ISLANDS (U.S.)", true),
            new Pais("WF", "WALLIS AND FUTUNA ISLANDS", true),
            new Pais("EH", "WESTERN SAHARA", true),
            new Pais("YE", "YEMEN", true),
            new Pais("ZM", "ZAMBIA", true),
            new Pais("ZW", "ZIMBABWE", true)
        );

        for (Pais pais : paises) {
            try {
                paisRepository.save(pais);
                log.info("✓ País creado: {} - {}", pais.getId(), pais.getNombre());
            } catch (Exception e) {
                log.error("Error al crear país {}: {}", pais.getNombre(), e.getMessage());
            }
        }

        log.info("Países de demostración creados exitosamente. Total: {}", paisRepository.count());
    }
}
