spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/facturita_main?currentSchema=public
    username: muglerman
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        default-schema: public
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

logging:
  level:
    root: INFO
    '[org.hibernate.SQL]': DEBUG
    '[org.hibernate.type.descriptor.sql]': TRACE
    '[org.springframework.web]': DEBUG
    '[com.cna.facturita]': DEBUG

jwt:
  secret: miSuperClaveJwtConMuchoTextoYCaracteresSeguros123!@#
  expiration: 3600000
