# =============================================================
# CONFIGURACIÓN PARA DATOS INICIALES EN MULTITENANT
# =============================================================

# Habilitar/deshabilitar carga de datos iniciales
facturita:
  data:
    load-initial-data=true
    load-demo-data=true

# Configuración de datos de demostración
  demo:
    create-companies=true
    create-users=true
    default-password=demo123

# Configuración de usuario administrador por defecto
  admin:
    default-email=admin@facturita.com
    default-password=admin123
    default-name=Administrador Sistema

# Configuración multitenant
  multitenant:
    enabled: true
    strategy: SCHEMA  # o DATABASE
    default-tenant: cna
# CORS para desarrollo
#setAllowedOriginPatterns
  cors:
    allowed-origin-patterns: "http://*.localhost:4200, http://*.localhost:3000, http://*/127.0.0.1:4200"


# =============================================================
# CONFIGURACIÓN DE BASE DE DATOS PARA MULTITENANT
# =============================================================

# Para desarrollo local
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/facturita_main
    username: muglerman
    password: 
    driver-class-name: org.postgresql.Driver

# Configuración JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        '[format_sql]': true

# Ejecutar scripts SQL automáticamente activar cuando ya se tenga el esquema, de never a always
  sql:
    init:
      mode: never
      data-locations: classpath:/data-multitenant.sql
      continue-on-error: true

# =============================================================
# LOGGING PARA DEBUGGING
# =============================================================

# Logs específicos para DataLoaders
logging:
  level:
    '[com.cna.facturita.api.config]': DEBUG

# Logs para SQL (opcional, útil para debugging)
    '[org.hibernate.SQL]': DEBUG
    '[org.hibernate.type.descriptor.sql.BasicBinder]': TRACE

# =============================================================
# CONFIGURACIÓN DE SEGURIDAD
# =============================================================

# JWT
jwt:
  secret: miSuperClaveJwtConMuchoTextoYCaracteresSeguros123!@#
  expiration: 3600000