spring:
  datasource:
    url: jdbc:postgresql://prod-host:5432/facturita_main
    username: prod_user
    password: prod_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    root: WARN
