spring:
  profiles:
    active: LOCAL # o prod en producción multitenant
  jackson:
    serialization:
      indent-output: true
  jpa:
    open-in-view: false
  main:
    banner-mode: "console"

server:
  port: 8080
